### PR TITLE
Added "Text Marker (Highlighter)"

### PR DESCRIPTION
**Pull request by ryu1kn**
## Name of an extension you are adding

Text Marker (Highlighter)

## Why do you think this extension is awesome?

This extension allows you to highlight multiple text patterns at the same time. Highlighting a single text pattern is possible by using the editor's search functionality, but it cannot highlight multiple patterns at the same time, and this is where this extension comes handy.

It helps you in the situations like following:

* To understand what's going on in the system by highlighting multiple keywords (like certain user id, ip address, ...) in log files (like access log, application log, ...)
* To be sure if system is correctly configured by highlighting multiple keywords through multiple source code or configuration files
* To understand which bit of code has reference to which variables/methods by highlighting all of them at the same while you read rather complex source code

Some details about features:

* Highlight colours are configurable
* Highlight patterns can be saved for next time you open the editor
* Pattern can be case sensitive/insensitive, partial/whole word, regular expression
* Pattern can be quickly updated through right-click menu

## Make sure that:

- [x] Screenshot/GIF included (to demonstrate the plugin functionality)
- [x] ToC updated

### CODE REVIEW

**Comment by ryu1kn** [comment]
I find this extension especially useful when I read logs or check multiple configuration files.

**Comment by viatsko** [comment]
I didn't understand the real use case for the plugin, from the description so far it looks like it is doing the same thing VS Code is already doing by default.

If I'm wrong, I'd like to see more detailed description explaining the benefit of using this plugin and how it extends the built-in functionality around text selection.

**Comment by ryu1kn** [comment]
I assume the vscode's default functionality you mentioned is "find". find can colour up only one text pattern at a time; if you want to colour up multiple text patterns at the same time with different colours, you can use Text Marker.

Suppose you're reading server access log or something. You could highlight user id, user agent, specific time range of timestamp at the same time. With them all highlighted it is easier to find correlations.

Gif animation may give you better picture of how it works

**Comment by ryu1kn** [comment]
@viatsko Just noticed that there was a conflict with the current master; so updated and resolved it. Can you have a look if you want to merge it?

**Comment by ryu1kn** [comment]
Also updated the PR comment using `PULL_REQUEST_TEMPLATE.md`

**Comment by viatsko** [comment]
It would be nice to mention the difference vs standard functionality of VS Code, this will make it clear why this extension is useful for users.

**Comment by ryu1kn** [comment]
@viatsko Added the following sentence in the PR description.

> Highlighting a single text pattern is possible by using the editor's search functionality, but it cannot highlight multiple patterns at the same time, and this is where this extension comes handy.

**Comment by viatsko** [comment]
Not exactly what I've meant, sorry, I should've been clearer. It should be added to extension description in a README.md as well.

**Comment by ryu1kn** [comment]
@viatsko Ah, you meant the description in the README file! 😅I've revised the description 👍

**Comment by viatsko** [comment]
LGTM now, thanks 👍

**Comment by ryu1kn** [comment]
Thank you @viatsko 👍

**Pull request merged**
