### PR TITLE
Add niketa theme

### PR DESCRIPTION
**Pull request by selfrefactor**
## Name of the extension you are adding
Niketa theme
...

## Why do you think this extension is awesome?

This collection of light themes is set in 4 groups with different background brightness. This allows usage of light theme during a bright light as well as during dark light conditions. 

Also, the theme was #1 trending theme for the last 7 days at 24-04-2019 timestamp: 

Trending Niketa
...

## Make sure that:

- [x] Screenshot/GIF included (to demonstrate the plugin functionality)

- [x] ToC updated

### CODE REVIEW

**Comment by jschr** [comment]
hey @selfrefactor, we'll need the build to pass before we can merge. I don't believe your changes are the reason it is failing. Maybe you need to pull the latest from this repo's master branch into your fork. Alternatively since the changes are small, you could re-fork this repo and submit another PR. Hope that works!

**Comment by selfrefactor** [comment]
@jschr I just synced with your master branch but still failing. Should I proceed to re-fork and submit a new PR?

**Comment by jschr** [comment]
@selfrefactor The build is failing because of some link that are now redirecting in the README. Looks like master has the same bad links (explains why updating from master didn't work). 

Could you update the links in the README their redirects according to the build output?

```
 1. [L0194] 301 https://marketplace.visualstudio.com/items?itemName=vicey.vscode-bond  → https://marketplace.visualstudio.com/items?itemName=yiwwan.vscode-bond 
 2. [L0769] 301 https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons  → https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons 
 3. [L1184] 301 https://themer.mjswensen.com  → https://themer.dev 
```

**Comment by selfrefactor** [comment]
@jschr I just did that and now it looks fine. Thank you for your help through the process.

**Comment by jschr** [comment]
Thank you!

**Pull request merged**
