### PR TITLE
Add vscode-caniuse under css category

### PR DESCRIPTION
**Pull request by agauniyal**

### CODE REVIEW

**Comment by mrmlnc** [comment]
Sorry, but this is a bad plugin. You have a dependency is a package that depends on `caniuse-db` which changes every day. It turns out that the users of your extension have stale data (or are you will update your plugin every day?).

**Comment by agauniyal** [comment]
Usually plugins are updated twice or thrice a month, so I'll go by it. Regarding caniuse-db being updated almost every day and extension having stale data, I assure the data will not be stale or wrong in this case, it would be slightly behind new additions. Saying it is stale is little exaggeration with the facts, since almost all previous properties are added to db.

If you'll notice, other plugins or cmd clients do depend on `caniuse-db` too and aren't updated everyday. In my opinion, these kind of plugins solve the problem for watching out semi-new properties ie. `svg`, `html5 features`, `flexbox properties` rather than properties which haven't even made into specs. So I guess updating 2 or 3 times per month is good enough for this case.

For now, I've also added a navigate in browser method that would give absolute latest information, however I could, in future, implement a solution that queries that data within the text editor itself, and only fallbacks to `caniuse-db` if network isn't available.

**Comment by viatsko** [comment]
First of all, great job, @agauniyal!

But, I agree with @mrmlnc here.

I'd recommend to look at https://github.com/akamud/vscode-caniuse code, it's not depending on `caniuse-db`. If plugin can implement both online and offline `caniuse` support, that would be much more great. However, I don't see any clear benefit between these two plugins, but we can consider adding both, explaining benefits.

**Comment by agauniyal** [comment]
Thankyou @viatsko , your words mean a lot 😄 .
I'll look into online + offline support (fetching data online and falling back to local db in case of failure) feature next week hopefully when I get some time.

**Pull request closed without merging**
