### PR TITLE
Add git-indicators

### PR DESCRIPTION
**Pull request by lamartire**
Just add my git extension.
Github: [https://github.com/lamartire/vscode-git-indicators](https://github.com/lamartire/vscode-git-indicators)
Marketplace: [https://marketplace.visualstudio.com/items?itemName=lamartire.git-indicators](https://marketplace.visualstudio.com/items?itemName=lamartire.git-indicators)

### CODE REVIEW

**Comment by viatsko** [comment]
Would like to have a gif which is showing exact functionality. The one which is on the GitHub is not a good fit for showing the functionality (the whole big window, while the feature is very very small).

**Comment by lamartire** [comment]
I just updated gif in main repo. How about that?

image

**Comment by viatsko** [comment]
Sorry for the delay. A small screenshot of feature alone would be enough :) It, with a combination with plugin name would be self-explaining

**Comment by lamartire** [comment]
Got it! I'll update pr tomorrow 😄

**Comment by lamartire** [comment]
Here is demo screenshots :tada:

**Comment by viatsko** [comment]
👍

**Comment by lamartire** [comment]
:ok_hand:

**Pull request merged**
