### PR TITLE
Alignment of contents of Table of Contents with actual contents

### PR DESCRIPTION
**Pull request by jonasbn**
Alignment of contents of Table of Contents with actual contents, Markdownlint reports some 108 issues, I only corrected a few easy ones, which would not interfere with the overall Markdown style of the README.

I have a branch addressing the remainder if you are interested 😜

### CODE REVIEW

**Comment by jschr** [comment]
Thanks 👍 

Looks good to me, @viatsko feel free to merge if it does to you.

**Comment by lannonbr** [comment]
Looks good to me as well. Thanks for the contribution @jonasbn!

**Comment by viatsko** [comment]
👍

**Comment by viatsko** [comment]
It's worth implementing Markdownlint as a part of a pipeline

**Comment by jonasbn** [comment]
PR #165 created - have a nice day.

**Pull request merged**
