### PR TITLE
Added material theme and updated one dark pro

### PR DESCRIPTION
**Pull request by athahersirnaik**
Previous Material theme was One dark Pro.

Added Original Material theme

### CODE REVIEW

**Comment by viatsko** [comment]
We are reworking themes section. Will merge as soon as we'll push an update.

**Comment by viatsko** [comment]
The screenshot doesn't really explain how the theme looks like

**Comment by viatsko** [comment]
PTAL @jschr

**Comment by jschr** [comment]
This PR isn't compatible with the updated themes section. Please take a look at the [contributing guidelines](https://github.com/viatsko/awesome-vscode/blob/master/CONTRIBUTING.md) and re-submit if you'd like to see these changes merged.

Thanks

**Pull request closed without merging**
