### PR TITLE
Add Cobalt2 Theme by Wes Bos

### PR DESCRIPTION
**Pull request by vpicone**

### CODE REVIEW

**Comment by akshayvinchurkar1** [comment]
This looks good

**Comment by viatsko** [comment]
Consider removing description paragraph, it's confusing. It doesn't include "some great tips", it includes instructions on using custom CSS in VS Code.

**Comment by vpicone** [comment]
@viatsko I removed the description paragraph :+1:

**Comment by viatsko** [comment]
👍

**Pull request merged**
