### PR TITLE
Included ES7 React/Redux/GraphQL/React-Native snippets under Productivity

### PR DESCRIPTION
**Pull request by Muljayan**
## Name of an extension you are adding
ES7 React/Redux/GraphQL/React-Native snippets

## Why do you think this extension is awesome?
It increases efficiency when working with nodejs/reactjs by enabling short codes to create repetitive functions/imports/exports etc

## Make sure that:

[ x] Screenshot/GIF included (to demonstrate the plugin functionality)
Doesn't included screenshot or GIF but contains a table to show examples of snippets
[ x] ToC updated

### CODE REVIEW

**Comment by Muljayan** [comment]
Hi @viatsko  this is the updated pr of #160 . I have made the changes as requested and resolved all merge conflicts.

**Comment by viatsko** [comment]
Thanks for the PR!

I still don't feel that including that table is needed. Maybe spoiler component can be a good option (not sure it's supported outside of GH wiki tho, but worth checking)

**Comment by Muljayan** [comment]
Hi @viatsko  , I was able to remove the table and include a screen shot. I believe it should be fine now.

**Comment by viatsko** [comment]
Thanks!

**Pull request merged**
