### PR TITLE
Add Dendron to Productivity extensions

### PR DESCRIPTION
**Pull request by ScriptAutomate**
## Name of the extension you are adding

Dendron

## Why do you think this extension is awesome?

> _Disclaimer: I started actively using Dendron early 2021 as a fan/user, and now I've recently joined the team behind Dendron._

[Dendron](https://www.dendron.so/) is a PKM tool that makes use of all VSCode/VSCodium already has to offer, along with a great feature set for managing knowledge via notes and documentation. There is also a CLI tool that uses NextJS as static site generator (SSG, like Jekyll/Hugo/etc. support) if wanting to make certain aspects of docs public, such as a blog or searchable second brain.

Another thing that's really cool is that you can import Dendron vaults (a git repo of notes) that are public, being able to turn your workspace into something like a distributed wiki. This is great as it allows people to make use of each others knowledge in an accessible fashion.

### Additional resource links

- Extension in marketplace: https://marketplace.visualstudio.com/items?itemName=dendron.dendron
- GitHub Org: https://github.com/dendronhq
- Website: https://www.dendron.so/
- Wiki (managed and published with the Dendron extension and `dendron-cli`): https://wiki.dendron.so/

There is also an active and growing community on the [Dendron Discord](https://discord.com/invite/xrKTUStHNZ).

## Make sure that:

- [x] Screenshot/GIF included (to demonstrate the plugin functionality)

- [x] ToC updated

### CODE REVIEW

**Comment by zardoy** [comment]
Hey! It's not really critical but since you're in the team, can you tell them to remove `dist/stats.json` (70MB) and `dist/extension.jsbak` from vsix bundle, it will reduce it by 5mb. I just really pay attention how the extensions are optimized, hope you will also do.

**Comment by kevinslin** [comment]
> Hey! It's not really critical but since you're in the team, can you tell them to remove `dist/stats.json` (70MB) and `dist/extension.jsbak` from vsix bundle, it will reduce it by 5mb. I just really pay attention how the extensions are optimized, hope you will also do.

Thanks for the pointer. We'll have them removed for the next release!

**Comment by ScriptAutomate** [comment]
@viatsko Wondering if there are any remaining tasks I need to take care of to get this added?

**Comment by kevinslin** [comment]
@viatsko ping to see if there's anything else needed to merge this pr?

**Comment by viatsko** [comment]
I was waiting to see more users installing extension keeping rating at solid A before making a decision on including an extension. I've also checked the data for alternatives, and indeed we can include this extension to the list now.

Thanks!

**Pull request merged**
