### PR TITLE
Added "Partial Diff"

### PR DESCRIPTION
**Pull request by ryu1kn**
Partial Diff. Allows you to execute not only file-to-file but more granular text comparisons.

### CODE REVIEW

**Comment by ryu1kn** [comment]
Hello @viatsko , just added Partial Diff to the README. Please have a look 😉

**Comment by ryu1kn** [comment]
Build failed. Looks like `prettier-vscode` extension has moved its repository?

```
Issues :-(
> Links 
  1. [L150] 301 https://github.com/esbenp/prettier-vscode  → https://github.com/prettier/prettier-vscode 
```

**Comment by viatsko** [comment]
Very creative and handy plugin! Compliments for developing it, also thanks for fixing prettier-vscode url!

**Comment by ryu1kn** [comment]
Thanks for the encouraging comments! 😉

**Pull request merged**
